-- MySQL Script generated by MySQL Workbench
-- Thu Oct 15 07:59:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usermanagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usermanagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usermanagement` DEFAULT CHARACTER SET utf8 ;
USE `usermanagement` ;

-- -----------------------------------------------------
-- Table `usermanagement`.`ID_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usermanagement`.`ID_type` ;

CREATE TABLE IF NOT EXISTS `usermanagement`.`ID_type` (
  `idID_type` INT NOT NULL,
  `ID_typename` VARCHAR(45) NULL COMMENT 'This include National ID, drivers liscence, international passport.',
  `ID_type_status` TINYINT(4) NULL COMMENT 'When in to be use or not to be use',
  `create_time` TIMESTAMP(5) NULL,
  `update_time` TIMESTAMP(5) NULL,
  PRIMARY KEY (`idID_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usermanagement`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usermanagement`.`country` ;

CREATE TABLE IF NOT EXISTS `usermanagement`.`country` (
  `idcountry` INT NOT NULL COMMENT 'This table will be used for forms if need',
  `country` VARCHAR(45) NULL,
  `countrycode` VARCHAR(10) NULL COMMENT 'for example +234',
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usermanagement`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usermanagement`.`state` ;

CREATE TABLE IF NOT EXISTS `usermanagement`.`state` (
  `idstate` INT NOT NULL COMMENT 'This table will be used for forms if needed.',
  `state` VARCHAR(45) NULL,
  `idcountry` INT NOT NULL,
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`idcountry`)
    REFERENCES `usermanagement`.`country` (`idcountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_state_country1_idx` ON `usermanagement`.`state` (`idcountry` ASC);


-- -----------------------------------------------------
-- Table `usermanagement`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usermanagement`.`user` ;

CREATE TABLE IF NOT EXISTS `usermanagement`.`user` (
  `userid` INT NOT NULL COMMENT 'This is to be used internally within the project because integer primary keys are faste.',
  `username` VARCHAR(45) NOT NULL COMMENT 'This is an indexed column. It is very important for authentication/login. This can be email or phone number.',
  `email` VARCHAR(45) NULL COMMENT 'This should be unique but can be not null',
  `password` VARCHAR(100) NULL COMMENT 'This should be encrypted. The length depends on the encryption method.',
  `phonenumber` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `resident_address` VARCHAR(250) NULL,
  `resident_city` VARCHAR(45) NULL,
  `resident_state` VARCHAR(45) NULL,
  `resident_country` VARCHAR(45) NULL,
  `countrycode` VARCHAR(10) NOT NULL COMMENT 'To be used with phonenumber',
  `user_role` VARCHAR(20) NULL COMMENT 'User roles for this project are user, driver and admin. Other roles can come in later. A user cannot have driver roles. A driver has user roles but not admin. Admin has both user and driver roles as well as admin roles',
  `user_status` TINYINT(4) NULL COMMENT 'A user can be 0-inactive or 1-active. A user is active when email or phone number is verified.',
  `user_verification_code` VARCHAR(45) NULL COMMENT 'To verify user and helpful for account recovery.',
  `user_verification_status` TINYINT(4) NULL COMMENT 'If verification code has expired or not.',
  `user_verification_start` TIMESTAMP(5) NULL,
  `create_time` TIMESTAMP(5) NULL COMMENT 'Time was created',
  `update_time` TIMESTAMP(5) NULL COMMENT 'Last time was created',
  `last_login` TIMESTAMP(5) NULL COMMENT 'Last time user logged in',
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `usermanagement`.`user` (`username` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `usermanagement`.`user` (`email` ASC);

CREATE UNIQUE INDEX `phonenumber_UNIQUE` ON `usermanagement`.`user` (`phonenumber` ASC);


-- -----------------------------------------------------
-- Table `usermanagement`.`user_ID`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usermanagement`.`user_ID` ;

CREATE TABLE IF NOT EXISTS `usermanagement`.`user_ID` (
  `iduser_ID` INT NOT NULL,
  `ID_number` VARCHAR(45) NOT NULL,
  `ID_file` VARCHAR(45) NULL,
  `ID_status` TINYINT(4) NULL COMMENT 'Whether verified or not',
  `create_time` TIMESTAMP(5) NULL,
  `update_time` TIMESTAMP(5) NULL,
  `userid` INT NOT NULL COMMENT 'One user has many ID especially drivers.',
  `idID_type` INT NOT NULL,
  PRIMARY KEY (`iduser_ID`),
  CONSTRAINT `fk_user_ID_user`
    FOREIGN KEY (`userid`)
    REFERENCES `usermanagement`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_ID_ID_type1`
    FOREIGN KEY (`idID_type`)
    REFERENCES `usermanagement`.`ID_type` (`idID_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ID_number_UNIQUE` ON `usermanagement`.`user_ID` (`ID_number` ASC);

CREATE INDEX `fk_user_ID_user_idx` ON `usermanagement`.`user_ID` (`userid` ASC);

CREATE INDEX `fk_user_ID_ID_type1_idx` ON `usermanagement`.`user_ID` (`idID_type` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
